name: Docker Image CI

on:
  push:
    branches:
    - release/*

jobs:

  check-out:
    runs-on: ubuntu-latest

    steps:
    
    - name: Check Out
      uses: actions/checkout@v3
      
  setup:
    needs: check-out
    runs-on: ubuntu-latest
          
    steps:
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
 
  build-and-push:
    needs: [check-out, setup]
    runs-on: ubuntu-latest

    steps:        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: archett0/workshop:v1.9.0

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Name: ${{secrets.NAME}} \n Matriculation: ${{secrets.MATRICULATION}} \n Email: ${{secrets.EMAIL}} \n Repo: ${{github.repositoryUrl}} \n Image name: ${{secrets.IMAGE_NAME}} \n Image URL: ${{secrets.IMAGE_URL}}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    
